FROM node:20-slim

RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . ./
RUN npx prisma generate

EXPOSE 3333
CMD ["npm", "run", "dev"]
